services:
  dev:
    platform: linux/amd64
    build:
      context: .
    environment:
      - KBC_RUNID
      - SNOWFLAKE_HOST
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_WAREHOUSE
    volumes:
      - ./:/code
      - ./data:/data
