version: '2'
services:
  dev:
    build:
      context: .
      args:
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    volumes:
      - ./:/code
      - ./data:/data
