services:
  dev:
    platform: linux/amd64
    build:
      context: .
    environment:
      - KBC_RUNID
      - HOST
      - USER
      - PASSWORD
      - DATABASE
      - WAREHOUSE
    volumes:
      - ./:/code
      - ./data:/data
